# Generated by Django 4.1 on 2022-08-19 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacher_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('teacher_name', models.CharField(max_length=100)),
                ('address', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
    ]
