# Generated by Django 4.1 on 2022-08-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_alter_teacher_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('c_code', models.CharField(max_length=100)),
                ('c_teacher', models.CharField(max_length=20)),
                ('faculty', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
    ]
